modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
modId="tov"
version="0.1"
displayName="Tales of Varmithore"
logoFile="tov.png"
credits="Kundzio, Ghanou Craft, Arsian, FeatherStorm208, NaniTheDuck, Ceadrisc, Happysg, Bluedude, It's Cat"
authors="Ghanou Craft, Kundzio"
description='''Tales of Varmithore.. A fantasy themed mod that will bring so much new content to your world!
'''
[[dependencies.tov]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tov]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
